### ISSUE TITLE
Fail during building

### ISSUE THREAD

**Issue by MattQ50** [BlindMindStudios/StarRuler2-Source#10]
As title says, when building on Visual Studio 2017 in both debug or non-steam versions, building crashes and exits with 2 failed processes.

Exact line:  9>LINK : fatal error LNK1181: cannot open input file 'angelscript64.lib'

**Comment by DaloLorn** [comment]
*sighs* AngelScript is a little finicky with Win64 builds, yes...

This procedure should fix the build:

1) Right-click the `angelscript` project in the solution browser to bring up its context menu
  - Select `Build Configurations -> Build Customizations`
  - Tick the checkbox whose contents begin with `masm` to enable MASM
2) In the solution browser, under `angelscript/Source Files`, find the file `as_callfunc_x64_msvc_asm.asm`.
  - Right-click that file and select `Exclude from Project`.
3) Right-click on `angelscript/Source Files`, and select `Add -> Existing Item`
  - Find the file `angelscript/source/as_callfunc_x64_msvc_asm.asm` in your SR2 repository and add it to the project.

**Comment by MattQ50** [comment]
Worked perfectly, thank you.
