### ISSUE TITLE
Can't build on Ubuntu 16.04 (libangelscript)

### ISSUE THREAD

**Issue by Vthyarilops** [BlindMindStudios/StarRuler2-Source#19]
It seems I can't build under Ubuntu 16.04, as far as I can tell I have all the required dependencies. error log here : https://pastebin.com/Fmy6kuaf

**Comment by diddledan** [comment]
you need to set `CC=g++` in your environment when executing `make`, OR change references to `$(CC)` to `$(CXX)` in the Makefile.

**Comment by Vthyarilops** [comment]
thanks for the reply, I've tried both and it gives the same error.

**Comment by rl-michels** [comment]
Try finding the makefile in ./source/angelscript/projects/gnuc and add the option "-std=c++11" to CXXFLAGS there. That seemed to fix the problem for me.

**Comment by Vthyarilops** [comment]
Thank you, that worked great, unfortunately I'm stuck on another error (I get the same error in an Ubuntu 18.04 VM) https://pastebin.com/UGkP48tn

**Comment by rl-michels** [comment]
That seems to be the same issue as #24 
To fix it you could try and follow the solution proposed by compenguy in #5

**Comment by Vthyarilops** [comment]
Thanks for the suggestion, I've already tried and end up with the same results (I assume the fix in issue #9 is the same as #24  and #5

**Comment by Vthyarilops** [comment]
Just want to thank BlindMindStudios, rl-michels, and diddledan, plays totally fine on Ubuntu 16.04 if libpng16-16 is installed and you copy libGLEW.so.2.0 to the main directory, it spits out some libpng errors but doesn't seem to affect gameplay, anyways thanks everyone.

**Comment by ethchest** [comment]
I installed libpng16-16 but from where do you copy libGLEW.so.2.0 ? I do not find it anywhere. Which package should have it? I did all the fixes by @compenguy but always get an error in makelibs about image.o
