### ISSUE TITLE
Make fails: unable to find freetype

### ISSUE THREAD

**Issue by se5a** [BlindMindStudios/StarRuler2-Source#26]
```make: *** No rule to make target '/usr/include/freetype2/freetype/freetype.h', needed by 'obj/lin64/render/font_ft2.o'. Stop.```

however it appears the source has freetype2 included in source folder: 
https://github.com/BlindMindStudios/StarRuler2-Source/tree/master/source/freetype2

I attempted to edit the makefile to point at this, but as I've got no clue what I'm doing, it didn't seem to make any difference to the error. 

on linux mint 18.3

**Comment by ethchest** [comment]
You have to install it. Afaik the included source is either for Windows or otherwise not used during compilation. `sudo apt install libfreetype6-dev libfonconfig1-dev libxft2-dev`

**Comment by se5a** [comment]
Ah yes it is possibly just the windows version in there. yep those ones did the trick for that. 
now onto figuring out other errors.
