### ISSUE TITLE
If i send a PR to there, has anyone reviewe it?

### ISSUE THREAD

**Issue by Sun-FreePort** [BlindMindStudios/StarRuler2-Source#40]
I want to add new locales/chinese, who can give some advice?

**Comment by DaloLorn** [comment]
Well, previous pull requests were reviewed. Don't know how long that will last, assuming it's not over yet, but there's no harm in trying.

**Comment by Sun-FreePort** [comment]
@DaloLorn Thanks! let's i do it.

**Comment by Sun-FreePort** [comment]
Where is `story.txt` file used?

https://github.com/BlindMindStudios/StarRuler2-Source/blob/ba99a9a30875a4b76ff60b919d11a2e13a32c4e7/locales/english/story.txt#L1-L16

**Comment by DaloLorn** [comment]
Nowhere. It's a relic of something that was present so early in development that I never even got to see it. (Well, aside from reenabling it manually to take a look at it.)

**Comment by Sun-FreePort** [comment]
All right, i skip it——but, i like story mode on sand box
