### ISSUE TITLE
Ringworlds crash my video card and the game even w/ "Safe Ringworlds"

### ISSUE THREAD

**Issue by l29ah** [BlindMindStudios/StarRuler2-Source#67]
Linux l29ah-x201 4.19.0-rc6+ #107 SMP PREEMPT Wed Oct 3 19:13:19 MSK 2018 x86_64 Intel(R) Core(TM) i5-3320M CPU @ 2.60GHz GenuineIntel GNU/Linux

**Comment by l29ah** [comment]
Eh, wrong project.

**Comment by DaloLorn** [comment]
Well, not entirely. :P
