### ISSUE TITLE
False claim that game is open source

### ISSUE THREAD

**Issue by Wuzzy2** [BlindMindStudios/StarRuler2-Source#8]
## The bug

This repository claims the game “Star Ruler 2” is open source. I am posting this issue here to notify you that this claim is false.
The media files are licensed under CC BY-NC.
CC BY-NC is *not* an open source license.
It is *not* apporoved by the Open Source Initiative and not considered to be an open source license under the open source definition (https://opensource.org/definition). This is not my own opinion, this is a widely accepted fact in the open source and free software communities.

Please fix this.

## Bugfix

There are two possible ways to fix this bug:

1. Release media files under an open source license like CC BY or CC BY-SA, thus making the game open source (here's a list of all OSI-approved open source licenses: https://opensource.org/licenses). OR …
2. Remove all claims of Star Ruler 2 being open source, thus fixing the false claim

Note:
If you are *truly* committed to open source, it would probably be an easy decision for you to release the media under an open source license as well.

Thank you for your attention.

**Comment by ThyReaper** [comment]
We are not truly committed to open source. The OSI doesn't control the use of the term 'open source.' This is silly pedantry, and I do not welcome it!

Also, the _**source**_ is open. The code uses assets, which we've decided to provide under a separate license.

**Comment by Wuzzy2** [comment]
I'm feeling sad for that to hear. :-(

Just out of interest, may I know the rationale for the non-free license? If do not like to disclose, I can totally understand.

And no, I do not think this is silly pedantry. The OSI was founded by Eric S. Raymond, the *inventor* of the term “open source”. They have all the right to define it. Also, the definition from OSI is very widely accepted in the open source and free software communities. So if you like to redefine the term “open source” to your liking, you are using an obscure definition which is not accepted by the vast majority. This obviously leads to confusion. Thus, this issue.
“Open source” does *not* just refer to the source code.

What this means for Star Ruler 2:

The game *as a whole* is not open source, since the code alone does not make a playable game.
The *code* is indeed open source.
The media is, as you know, not open source.

So if you simply say (in the readme, repository description, etc.), the game's *code* is open source, instead of claiming the entire *game* is open source, that would be a truthful sentence. Very simple.

Finally: I want to make absolutely clear I did not intend to attack you or this game in any way or imply that any of the people involved are bad people. I just don't like it to see terms with a long hisotry being used incorrectly. Surely, no harm would be done by just clarify all that in a few sentences?

**Comment by ThyReaper** [comment]
The nice person who made the content requested the license. The likely alternative would be that this distribution would contain no free content, only the source code. The program doesn't require any content, after all.

**Comment by Wuzzy2** [comment]
Ah, okay, thanks for the info.

Is there any way to contact the person who made the art?

**Comment by DaloLorn** [comment]
@Wuzzy2 This was previously discussed in issue #2, where Jon explained his reasons for wanting the assets to be under an NC license, and I speculated as to why Blind Mind might want to use the current license even before taking Jon into consideration.

Also, realistically, if you're trying to use this stuff commercially, you've already got a lot more than you could reasonably expect most people to give you. You've got a very solid engine, the source code for that engine, and all the gameplay scripts/data - adding assets to the mix is comparably easy, so long as you've got a competent artist or two.

SR2's asset workflow may seem a little quirky at times, but it's also pretty consistent. In the years I've spent modding it, I've managed to introduce new assets of every kind (except OGEX models - I only used OBJ) with very little difficulty. Granted, I didn't always do a very good job of it, but the blame for that lies with my limited skills and the fact that I was mostly just porting things from other games.

**Comment by emorrp1** [comment]
@ThyReaper Agreed! The game as a whole is open source, though it may not be "Open Source" or "Free Software", but the *engine* definitely is. I think it's important to encourage developers to do exactly what you have done, to release the game code when it's no longer commercially useful, because it avoids unnecessary duplication of effort to recreate (see https://osgameclones.com/). Even better that you have also released the assets gratis. Thank you again.

**Comment by DaloLorn** [comment]
Also, technically, the game *is* free software - you can build and play it just fine, you just can't commercialize it as long as it includes any of the original assets.

**Comment by jdoe0** [comment]
@DaloLorn 

>Also, technically, the game is free software

I would just like to point out that the term [*free software*](https://en.wikipedia.org/wiki/Free_software) has a specific definition, meaning software that satisfies [*the free software definition*](https://en.wikipedia.org/wiki/The_Free_Software_Definition). Having a non-commercial restriction is at odds with this definition.

I believe the term you are thinking of is [*freeware*](https://en.wikipedia.org/wiki/Freeware).
