### ISSUE TITLE
Xubuntu/Ubuntu 222

### ISSUE THREAD

**Issue by GH-MrSomebody** [BlindMindStudios/StarRuler2-Source#84]
Rather than add this to several  (b/c they're all outdated!) 
 _**was anybody able to get this to work on Xubuntu/Ubuntu 22 ?**_

Worked through dependencies for *HOURS*  [only some of which were listed] but finally gave up.  
[doesn't help that nearly all posts R outdated,  trying to "fix" stuff w advice given 10+ years ago!  [no joke!]  
Yes,  95%  no longer relevant.  
Example:  [this was from here,  Github]  "software center" ----OMG can't tell you how many times somebody has said that, & it *MAY* have once been true,  but even 2 versions later,  what's offered/avail there,  changes---a LOT. 

Anyway now get a *REALLY* long mess when try to compile,  don't even understand all of it!  
(clipped from start, terminal won't display it all!)
..... 
[SR2_Errors.txt](https://github.com/BlindMindStudios/StarRuler2-Source/files/10903392/SR2_Errors.txt)

**Comment by Skeletonxf** [comment]
We have CI producing builds for Ubuntu on this fork https://github.com/OpenSRProject/OpenStarRuler, also see the launchpad for a GUI installer https://github.com/OpenSRProject/OpenStarRuler-Launchpad

**Comment by GH-MrSomebody** [comment]
https://github.com/OpenSRProject/OpenStarRuler

Sorry I don't see it ---even tried a search for "Ubuntu" -  no luck

Will try the launchpad thing---thanks.

**Comment by GH-MrSomebody** [comment]
sorry,  didn't realize packages were *slightly* different!  
https://github.com/OpenSRProject/OpenStarRuler
using package from there 2 overwrite existing SR2 package  [much larger]   hope that's right?
trying "make" now.......

**Comment by GH-MrSomebody** [comment]
OMG I GOT A BIN FILE!!!   ***  WOO HOO  THANK  YOU!!!  *****

**Comment by GH-MrSomebody** [comment]
seriously,  *REALLY* need to clarify that that one [& how to overwrite it!]  is for Xubuntu/Ubuntu.  
Nothing about it in readme.

**Comment by GH-MrSomebody** [comment]
YEA WORKING!!!   God bless you [Skeletonxf](https://github.com/Skeletonxf) !!!

**Comment by DaloLorn** [comment]
It sounds like you kept trying to build the game yourself? You could have just downloaded the prebuilt binaries from https://github.com/OpenSRProject/OpenStarRuler/tags - I think that's what Skeleton was trying to suggest, considering his mention of the CI.

On the bright side, it sounds like you figured out the build after all, which I think puts you a step ahead of me! 😂 (I only ever managed to build the game once, and it was on Windows.)

**Comment by GH-MrSomebody** [comment]
Didn't even know that was an option! 

I'm no Linux expert  but do know dependencies vary quite a bit from "flavor" or "version",  I assumed binaries did too?

The link Skeleton  gave me was Ubuntu specific,  & it wasn't big,  but must've had whatever file(s) ?  I was missing! 

Did u use Visual Studio 2017?
Haven't used that version,  but tried an older one a while back---royal pain,   wasn't easy either.
=======================================================
-->>  People talk a lot about  "AI"  [complete BS]  & there's  been some good talks about how to test intelligence, SHOW ME SOMEONE WHO CAN PROGRAM, or, even simpler,  troubleshoot, detect, & fix,  20+ dependencies [or,  say,  40+ "bugs"  that keep a program from running properly], 
that,  now,  *THAT*,  takes INTELLIGENCE!
_Machines can *BE* programmed,  but they can't program anything themselves._  


PS not on Github much,  not even sure why that section is Bold/larger lol!

**Comment by GH-MrSomebody** [comment]
thanks 2 everyone who helped!  :-)
