### ISSUE TITLE
Insanely long build error. Any help EXTREMELY APRECIATED.

### ISSUE THREAD

**Issue by SPLATPLAYS** [BlindMindStudios/StarRuler2-Source#87]
I have this really long build error. Can someone help reslove this issue.

I ran ""sudo make -f source/linux/Makefile compile > output.txt 2>&1"" so i could share the output.
[output.txt](https://github.com/BlindMindStudios/StarRuler2-Source/files/14865893/output.txt)

**Comment by SPLATPLAYS** [comment]
Be warned this is a 2mb output

**Comment by DaloLorn** [comment]
Any Linux guys who could take a stab at it? I'm out of my depth here.

@SPLATPLAYS If you haven't tried yet, you could try to install the game via the [OpenSR Launchpad](https://github.com/OpenSRProject/OpenStarRuler-Launchpad/releases/tag/v2.0.1). The automated builds for Linux have been a mixed bag, but if you're only looking to play, that might help out.

**Comment by SPLATPLAYS** [comment]
Thanks, I'll certainly give it a go.

**Comment by SPLATPLAYS** [comment]
Halfway

**Comment by SPLATPLAYS** [comment]
@DaloLorn I have tried to use OpenSR Launchpad. I installed its copy of the game separately. 

When I press the play button Nothing happens.

**Comment by DaloLorn** [comment]
... What happens if you try to run the game directly from terminal? There's a launch script in the root directory that should do the trick.

**Comment by SPLATPLAYS** [comment]
sudo ./StarRuler2.sh
chmod: cannot access './bin/lin64/StarRuler2.bin': No such file or directory
./StarRuler2.sh: line 16: /home/myusernamelol/StarRuler2-Source/bin/lin64/StarRuler2.bin: No such file or directory

**Comment by SPLATPLAYS** [comment]
@DaloLorn

**Comment by DaloLorn** [comment]
Uhh... this looks like you're trying to run the game from the uncompiled source, rather than the copy you installed via the Launchpad. That obviously wouldn't work, but I'm wondering why the Launchpad copy isn't starting, so you'll need to use that one's launch script instead.

(No need to explicitly ping me, by the way, least of all in a separate comment: I'm getting GitHub email notifications for each comment, *and* there's a webhook posting all of this into the OpenSR Discord. As long as you post *any comment* at all, there's nothing you can do to control how quickly I see it.)

**Comment by SPLATPLAYS** [comment]
Ok, sorry about the pings, I misunderstood. Here is my next error message: ./StarRuler2.sh
./bin/lin64/StarRuler2.bin: error while loading shared libraries: libGLEW.so.2.1: cannot open shared object file: No such file or directory

**Comment by DaloLorn** [comment]
That'll be related to [this](https://github.com/OpenSRProject/OpenStarRuler/issues/13), then. Ubuntu bundles GLEW 2.2 nowadays. Fortunately, the user opening that issue also offered a convenient workaround in his opening post, so you should be good to go once you've done that!

**Comment by SPLATPLAYS** [comment]
Thanks so much. 
![image](https://github.com/BlindMindStudios/StarRuler2-Source/assets/122862439/eb09daa2-8cea-464b-b3e6-e06eba6a8d29)
I'll go play it now.
